name: Get PR Labels

on:
  pull_request:
    types:
      - opened

jobs:
  get_labels:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Get PR Labels
      shell: pwsh
      run: |
        # Extract the labels from the GitHub context in PowerShell
        $prLabels = $env:{{ github.event.pull_request.labels.*.name }}

        # Output the labels
        Write-Output "PR Labels: $($prLabels -join ', ')"
