name: Read PR Labels

on:
  pull_request:
    types:
      - labeled

jobs:
  read-labels:
    runs-on: self-hosted

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Install GitHub CLI
      run: |
        gh --version

    - name: Fetch PR labels
      run: |
        $PR_NUMBER=$env:GITHUB_EVENT_PULL_REQUEST_NUMBER

        # Fetch pull request labels using GitHub CLI
        $PR_LABELS=gh pr view $PR_NUMBER --json labels -q '.labels[].name'

        Write-Host "Labels for PR#$PR_NUMBER: $PR_LABELS"
