name: Read PR Labels

on:
  pull_request:
    types:
      - labeled

env:
  GIT-FOLDER-PATH: 'C:\Users\spachipala\projects\test'

jobs:
  read-labels:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
      with:
         fetch-depth: 2
    
    - name: Extract the Label
      id: extract-label
      run: |
        $Events = Get-Content $env:GITHUB_EVENT_PATH | ConvertFrom-Json | Select-Object -ExpandProperty number
        $Labels = Get-Content $env:GITHUB_EVENT_PATH | ConvertFrom-Json | Select-Object -ExpandProperty pull_request | Select-Object -ExpandProperty labels
        $FirstLabel = $Labels[0].name
        Write-Host "Events: $Events"
        Write-Host "First Label: $FirstLabel"
        echo "Events=$Events"
        echo "FIRST_LABEL=$FirstLabel" >> $ENV:GITHUB_OUTPUT

    - name: Get changes
      run: |
         git fetch origin main
         $changes = git diff --name-only --diff-filter=d main~ main
         Write-Host "changes: $changes"
