name: Read PR Labels

on:
  pull_request:
    types:
      - labeled

jobs:
  read-labels:
    runs-on: self-hosted

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up GitHub CLI
      run: |
        sudo apt-get install -y gh
        gh --version

    - name: Fetch PR labels
      run: |
        PR_NUMBER=${{ github.event.pull_request.number }}

        # Fetch pull request labels using GitHub CLI
        PR_LABELS=$(gh pr view ${PR_NUMBER} --json labels -q '.labels[].name')

        echo "Labels for PR#${PR_NUMBER}: $PR_LABELS"
