name: Read PR Labels

on:
  pull_request:
    types:
      - labeled

env:
  GIT-FOLDER-PATH: 'C:\Users\spachipala\projects\test'

jobs:
  read-labels:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    
    - name: Extract the Label
      id: extract-label
      run: |
        $Events = Get-Content $env:GITHUB_EVENT_PATH | ConvertFrom-Json | Select *
        $Labels = Get-Content $env:GITHUB_EVENT_PATH | ConvertFrom-Json | Select-Object -ExpandProperty pull_request | Select-Object -ExpandProperty labels
        $FirstLabel = $Labels[0].name
        Write-Host "Events: $Events"
        Write-Host "First Label: $FirstLabel"
        echo "FIRST_LABEL=$FirstLabel" >> $ENV:GITHUB_OUTPUT
        echo "Events=$Events" >> $ENV:GITHUB_OUTPUT

    - name: Use Label
      if: contains(steps.extract-label.outputs.FIRST_LABEL, 'DB')
      working-directory: ${{ env.GIT-FOLDER-PATH }}
      run: |
        $FirstLabel = "${{ steps.extract-label.outputs.FIRST_LABEL }}"
        $FirstLabel =  $FirstLabel.Substring(3,($FirstLabel.Length)-3)
        Write-Host "Using First Label: $FirstLabel"
        .\test_CICD.ps1 $FirstLabel
        
     
         
     
