name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run PowerShell Script
      shell: pwsh
      run: |
         hostname
         pwd
         ls
