name: Get PR Labels

on:
  pull_request:
    types:
      - opened
  workflow_dispatch:

jobs:
  get_labels:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Get PR Labels
      run: |
        # Extract the labels from the GitHub context
        $prLabels = ${{ join(', ', github.event.pull_request.labels.*.name) }}

        # Output the labels
        echo "PR Labels: $prLabels"
